#' filter data interactive
#'
#' @description Interactive filtering of awk filtered data. Awk files may miss colnames. make shure they have colnames(data)="timestamp", "samples", "duration", "signal_freq", "signal_bw", "max_signal","noise", "receiver", "station"
#'
#'
#' @author Jannis Gottwald
#'
#'
#' 
#' @param animal list, generated by initanimal function
#' @param projList list, generatet by initProject function
#' @param station string, path to awk filtered file
#' @param nth num, subset data for plotting using only every nth column
#' @param version string, string pattern specifying the version of data processing
#' 
#'
#' @export
#'
#'





filter_interactive<-function(projList, animal, path_to_data=".", nth, version="."){
  

  stat<-data.table::fread(path_to_data)
 
  if(all(!(c("timestamp", "samples", "duration", "signal_freq", "signal_bw", "max_signal","noise", "receiver", "station") %in% colnames(stat)))){
   colnames(stat)<-c("timestamp", "samples", "duration", "signal_freq", "signal_bw", "max_signal","noise", "receiver", "station")}
  
  stat<-stat[!is.na(stat$timestamp),]
  tmp = stat[seq(1, nrow(stat), nth), ]
  print(plot(x=tmp$signal_freq, y=tmp$max_signal, ylim=c(45,100),panel.first=grid(ny=10)))
  


  if(continue()=="Y"){
    
  cat("Do you want to cut off the data in the upper dB range because, for example, another transmitter is interfering? If not, enter a value that lies above your distribution e.g. 120.")
  c1<-where_cut()
  stat<-stat[stat$max_signal<=c1,]
  
  
  done<-FALSE
  
  while(!done){
    
    stat<-stat[!is.na(stat$timestamp),]
    tmp = stat[seq(1, nrow(stat), nth), ]
    print(plot(x=tmp$signal_freq, y=tmp$max_signal, ylim=c(45,100),panel.first=grid(ny=10)))
    
    dat<-stat
    
    cat("Next, you can cut off the data below a value to the right and left of the centre frequency.Here, the entire umbrella-shaped distribution is roughly cut out - e.g. <80dB left (-3) right (+10).")
  lst1<-upper_cut()
  lst1<-unlist(lst1)
  
  dat$sig_diff<-dat$signal_freq-(animal$meta$freq)
  
  dat<-dat[!(dat$max_signal<=lst1[1] & (dat$sig_diff<=lst1[2] | dat$sig_diff>=lst1[3])),]
  
  tmp = dat[seq(1, nrow(dat), nth), ]
  print(plot(x=tmp$signal_freq, y=tmp$max_signal, ylim=c(45,100) ,panel.first=grid(ny=10)))
  
  s<-success()
  done <- s =="Y"
  
  if(done=="Y"){cat("next filter step")}
  if(done=="N"){cat("Back to ")}
  
  }
  
  done<-FALSE
  
  while(!done){
    
    cat("here, below the umbrella, the stem is cut out a little finer. e.g. below 60dB left(-0.5) and right (1)")
    
    dat2<-dat
    tmp = dat2[seq(1, nrow(dat), nth), ]
    print(plot(x=tmp$signal_freq, y=tmp$max_signal, ylim=c(45,100),panel.first=grid(ny=10)))
    
    
    

    lst2<-upper_cut()
    lst2<-unlist(lst2)
    dat2<-dat2[!(dat2$max_signal<=lst2[1] & (dat2$sig_diff<=lst2[2] | dat2$sig_diff>=lst2[3])),]
    
    tmp = dat2[seq(1, nrow(dat), nth), ]
    print(plot(x=tmp$signal_freq, y=tmp$max_signal, ylim=c(45,100),panel.first=grid(ny=10)))
    
    s<-success()
    done <- s =="Y"
    
    if(done=="Y"){cat("next filter step")}
    if(done=="N"){cat("Back to ")}
    
  }
  
  
  done<-FALSE
  while(!done){
    #tmp = dat[seq(1, nrow(dat), 100), ]
    print(plot(x=tmp$signal_freq, y=tmp$max_signal, ylim=c(45,100) ,panel.first=grid(ny=10)))
    
    
    df<-dat2
    cat("Here you can specify between which lower and upper dB value the mean frequency and the standard deviation should be calculated. e.g. lower 55 upper 60 ")
  lst3<-fun_fine()

  lst3<-unlist(lst3)
  print(lst3)
  
  tmp<-tmp[!is.na(tmp$max_signal),]
  mid_freq<-mean(tmp[tmp$max_signal>=lst3[1] & tmp$max_signal<=lst3[2],]$signal_freq)
  print(mid_freq)
  sd_freq<-4*sd(tmp[tmp$max_signal>=lst3[1] & tmp$max_signal<=lst3[2],]$signal_freq)
  print(sd_freq)
  
  cat("If the standard deviation is less than 1 and the mean frequency is in the range of the transmitter frequency, then answer with Y ")
  ok<-fun_param_okay(mid_freq = mid_freq, sd_freq = sd_freq)
  
  if(ok=="Y"){
  
  df$sig_diff<-abs(df$signal_freq-(mid_freq))
  
  cat("From where should the standard deviation be used to cut out? As a rule, a value just above the garbage carpet.")
  c<-where_cut()
  
  df<-df[!(df$max_signal<=c & df$sig_diff>=sd_freq),]
  tmp = df[seq(1, nrow(df), nth), ]
  print(plot(x=tmp$signal_freq, y=tmp$max_signal, ylim=c(45,100), panel.first=grid(ny=10)))
  
  
  s<-success()
  done <- s =="Y"
  
  if(done=="Y"){cat("station successfully filtered")}
  if(done=="N"){cat("Back to ")}
  
  
  }}
  
  param<-data.frame(cut_rough_max_signal=lst1[1], cut_rough_freq_er=lst1[2], cut_lower=lst2[1], cut_upper=lst2[2], sd=sd_freq, mid_freq=mid_freq, station=stat$station[1], ID=animal$meta$animalID)
  
  write.csv(param,paste0(projList$path$param_lst, "/", animal$meta$animalID,"_",df$station[1], "_filter_parameter.csv"))
  
  data.table::fwrite(df, paste0(animal$path$filtered, "/",df$station[1],"_",version, "_filtered.csv"))
  
  
}}










