#' create variables for ML
#'
#' @description Creates different variables from raw VHF signals to support machine learning
#'
#'
#' @author  Jannis Gottwald
#'
#' @param path_to_data string, path to station data
#' @param animal list, generated by initAnimal function
#' @param w numeric, window size for rollaply
#'
#' @export
#'
#'






machine_vars<-function(path_to_data,animal, w=c(5,11) ){
  
  data<-data.table::fread(path_to_data)
  
  if(is.na(data[1,1])){data<-data[,-1]}
  
  names(data)<-as.character(data[1,])
  data<-data[-1,]
  
  
  names(data)[names(data) == "0"] <- "a_0"
  names(data)[names(data) == "1"] <- "a_1"
  names(data)[names(data) == "2"] <- "a_2"
  names(data)[names(data) == "3"] <- "a_3"
  
  data$`a_0`<-imputeTS::na_interpolation( data$`a_0`, option ="linear", maxgap = 10)
  data$`a_1`<-imputeTS::na_interpolation( data$`a_1`, option ="linear", maxgap = 10)
  data$`a_2`<-imputeTS::na_interpolation( data$`a_2`, option ="linear", maxgap = 10)
  data$`a_3`<-imputeTS::na_interpolation( data$`a_3`, option ="linear", maxgap = 10)
  
  
  
  ############## w 10
  
  
  ##signal difference
  
  data$sigDiff_0_1<-data$`a_0`-data$`a_1`
  data$sigDiff_1_2<-data$`a_1`-data$`a_2`
  data$sigDiff_2_3<-data$`a_2`-data$`a_3`
  data$sigDiff_3_0<-data$`a_3`-data$`a_0`
  data$sigDiff_0_3<-data$`a_0`-data$`a_3`
  
  
  colms<-c("a_0","a_1", "a_2", "a_3", "sigDiff_0_1", "sigDiff_1_2", "sigDiff_2_3", "sigDiff_3_0", "sigDiff_0_3")
  
  from<-grep(colms[1], colnames(data))
  to<-grep("sigDiff_0_3",colnames(data))
  data<-scale.many_sc(data, cols=c(from:to))
  
  data<-normalize.many_sc(data, cols=colms)
  data<-rollaply.many(dat=data, cols=colms,funs=c("mean", "median", "max"), window=w[1] )
  data<-rollaply.many(dat=data, cols=colms,funs=c("mean", "median", "max"), window=w[2] )
  
  
  data.table::fwrite(data, paste0(animal$path$vars, "/",data$station[1], "ML_variables.csv"))
  
}





normalize <- function(x){(x-mean(x, na.rm = T))/sd(x, na.rm = T)}
normalize.many<- function(dat, cols) {
  nms <- names(dat)
  for(col in cols) {
    name <- paste(nms[col],"_normalized", sep = "")
    dat[name] <- normalize(dat[,col])
  }
  cat(paste("normalize ", length(cols), " variable(s)\n"))
  dat
}


rollaply.many<-function(dat, cols, funs=c("mean", "median", "max", "var", "sd"), window=5) {
  nms <- names(dat)
  for(col in cols) {
    dat<-as.data.frame(dat)
    
    for(f in funs){
      name <- paste0(f, "_",nms[col],"_",  "w", window)
      
      name<-gsub("a_", "", name)
      print(name)
      
      
      
      dat[name] <- zoo::rollapply(data=dat[,col], width=window, align="center", fill=NA, FUN=f)
    }}
  cat(paste(funs, length(cols), " variable(s)\n"))
  dat
}





scale.many<- function(dat, cols) {
  dat<-as.data.frame(dat)
  nms <- names(dat)
  for(col in cols) {
    name <- paste(nms[col],"_scaled", sep = "")
    dat[name] <- scale(dat[,col])
  }
  cat(paste("Scaled ", length(cols), " variable(s)\n"))
  dat
}



normalize.many_sc <- function(dat, cols) {
  nms <- names(dat)
  for(col in cols) {
    name <- paste(nms[col],"_nm", sep = "")
    dat[name] <- normalize(dat[,col])
  }
  cat(paste("normalize ", length(cols), " variable(s)\n"))
  dat
}


scale.many_sc <- function(dat, cols) {
  dat<-as.data.frame(dat)
  nms <- names(dat)
  for(col in cols) {
    name <- paste(nms[col],"_sc", sep = "")
    dat[name] <- scale(dat[,col])
  }
  cat(paste("Scaled ", length(cols), " variable(s)\n"))
  dat
}



